- name: varibles from files
  hosts: localhost
  tasks:
    vars_files:
      - variables.yaml
    - name: check varibles
      ansible.builtin.debug:
       msg: "I'm Learing {{Course}}, Duration is {{Duration}}, Trainer is {{Trainer}}"
