- name: Varibles from playlevel
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter user
    private: false
  - name: PASSWORD
    prompt: enter password
    private: true
    tasks:
  - name: check and print the names from prompt
    ansible.builtin.debug:
      msg: "User name {{USERNAME}}, password is {{PASSWORD}}"

