- name: Data types
  hosts: localhost
  vars:
    NAME: Rajanikanth
    Skills:
    - DevOps
    - AWS
    - ANsible
    - Terraform
    - Docker
    - K8
    Experience:
      DevOps: 3
      AWS: 3
      ANsible: 3
    Trainer: false
  tasks:
    - name: Print keyvalue pair
      ansible.builtin.debug:
        msg: "name is {{NAME}}"
  
    - name: Print from list
      ansible.builtin.debug:
        msg: "skill is {{Skills}}"

    - name: Print from map
      ansible.builtin.debug:
        msg: " experience is {{Experience}}"
    
    - name: Print from liBooleanst
      ansible.builtin.debug:
        msg: " trainer are {{Trainer}}
"
